sf/app/contractor/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, BooleanField
from wtforms.validators import InputRequired, NumberRange, Length


class ContractorForm(FlaskForm):
    id = IntegerField('PT ID', validators=[InputRequired('IDを入力して下さい。'),
        NumberRange(min=1, max=999999, message='有効なIDを入力して下さい。')])
    name = StringField('PT名', validators=[InputRequired('業者名は必須です。')])
    title = StringField('代表者役職名')
    representative = StringField('代表者名', validators=[InputRequired('代表者名は必須です。')])
    zip = StringField('郵便番号', validators=[InputRequired('郵便番号は必須です。'),
        Length(min=7, max=7, message='郵便番号は7桁です。')])
    prefecture = StringField('都道府県', validators=[InputRequired('都道府県は必須です。')])
    city = StringField('市区町村', validators=[InputRequired('市区町村は必須です。')])
    town = StringField('町域', validators=[InputRequired('町域は必須です。')])
    address = StringField('住所', validators=[InputRequired('住所は必須です。')])
    bldg = StringField('建物名等')
    care = BooleanField('サティスケア会員')

sf/app/contractor/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

from ..extentions import db

from ..models import Contractor, Satiscare, License, Permit

from .forms import ContractorForm

contractor = Blueprint('contractor', __name__, url_prefix='/contractor')

@contractor.route('/')
def index():

    q = request.args.get('q')
    page = request.args.get('page', 1, type=int)

    if q:
        search = "%{}%".format(q)
        contractors = Contractor.query.filter(Contractor.name.like(search)).paginate(page=page, per_page=20)
        count = len(Contractor.query.filter(Contractor.name.like(search)).all())

        return render_template('contractor/index.html', page=page, contractors=contractors, count=count, search=search)

    else:
        contractors = Contractor.query.paginate(page=page, per_page=20)
        count = len(Contractor.query.all())

        return render_template('contractor/index.html', contractors=contractors, page=page, count=count)


@contractor.route('/register', methods=['GET', 'POST'])
def register():

    form = ContractorForm()

    if form.validate_on_submit():

        id = request.form['id']

        # check if id already exists in the db
        exists = Contractor.query.get(id)

        if exists:
            return redirect(url_for('contractor.profile', id=id))

        else:
            name = request.form['name']
            title = request.form.get('title')
            representative = request.form['representative']
            zip = request.form['zip']
            prefecture = request.form['prefecture']
            city = request.form['city']
            town = request.form['town']
            address = request.form.get('address')
            bldg = request.form.get('bldg')
            registered_by = 1
            care = request.form.get('care')

            contractor = Contractor(id=id, name=name, title=title, representative=representative, zip=zip,
             prefecture=prefecture, city=city, town=town, address=address, bldg=bldg, registered_by=registered_by)

            db.session.add(contractor)

            if care:
                care = Satiscare(contractor_id=id, membership=True)
                db.session.add(care)

            db.session.commit()

            flash('パートナーを登録しました。', 'success')

            return redirect(url_for('contractor.profile', id=id))

    return render_template('contractor/register.html', form=form)


# show and update contractor profile
@contractor.route('/<int:id>')
@contractor.route('/<int:id>/<mode>', methods=['GET', 'POST'])
def profile(id, mode=None):

    contractor = Contractor.query.get(id)

    licenses = License.query.filter(License.contractor_id == id).all()
    permits = Permit.query.filter(Permit.contractor_id == id).all()

    if mode == 'edit':
        form = ContractorForm(obj=contractor)
        form.care.checked = Satiscare.query.filter_by(contractor_id = id).first()

        if form.validate_on_submit():

            contractor.name = request.form['name']
            contractor.title = request.form.get('title')
            contractor.representative = request.form['representative']
            contractor.zip = request.form['zip']
            contractor.prefecture = request.form['prefecture']
            contractor.city = request.form['city']
            contractor.town = request.form['town']
            contractor.address = request.form.get('address')
            contractor.bldg = request.form.get('bldg')
            contractor.registered_by = 1

            # if care checkbox is checked
            care = request.form.get('care')

            # if already a satiscare member 
            is_member = Satiscare.query.filter_by(contractor_id=id).first()

            if is_member and not care:
                member = Satiscare.query.filter_by(contractor_id=id).first()
                db.session.delete(member)

            elif not is_member and care:
                care = Satiscare(contractor_id=id, membership=True)
                db.session.add(care)

            else:
                pass

            db.session.commit()

            flash('パートナー情報を更新しました。', 'success')

            return redirect(url_for('contractor.profile', id=id))

        return render_template('contractor/edit.html', contractor=contractor, form=form)

    return render_template('contractor/profile.html', contractor=contractor, licenses=licenses, permits=permits)

sf/app/templates/contractor/edit.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}
{% from "_macros.html" import render_field_with_errors, render_input_field %}

<div class="container mx-auto max-w-sm py-10">
    <h1 class="font-bold text-xl text-gray-500">パートナー情報の更新</h1>

    <form action="/contractor/{{ contractor.id }}/edit" method="POST">
        {{ form.csrf_token }}
        
        <div class="my-5 text-gray-800">
            <h2 class="text-lg font-bold">{{ form.id(value=contractor.id, readonly=True) }}</h2>
        </div>

        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.name, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.title, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.representative, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.zip, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="flex my-3 text-gray-500">
            {{ render_input_field(form.prefecture, class_="w-full border-b px-3 text-lg", readonly=True)}}
            {{ render_input_field(form.city, class_="w-full border-b px-3 text-lg", readonly=True)}}
            {{ render_input_field(form.town, class_="w-full border-b px-3 text-lg")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.address, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.bldg, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>

        <div class="my-3 text-sm">
            {{ form.care.label(class_="text-base text-gray-500") }}
            {{ form.care(class_="border mx-3 align-middle") }}
        </div>

        <button type="submit" class="bg-blue-600 text-white text-sm my-5 py-1 px-28 w-full rounded shadow-lg
    hover:bg-blue-800 transition duration-200">登録</button>

    </form>
</div>
{% endblock %}

{% block script %}
<!-- 住所補完JavaScriptライブラリの読み込み -->
<script type="text/javascript" src="https://postcode-jp.com/js/postcodejp.js" charset="utf-8"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/postcode.js') }}"></script>
{% endblock %}

sf/app/templates/contractor/index.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}

<div class="container mx-auto max-w-4xl flex-grow">

    <div class="mx-auto my-12 max-w-md">

        <div class="flex justify-between my-5 ">
            <h1 class="font-bold text-xl text-gray-500">パートナー</h1>

            <a href="/contractor/register" class="text-sm text-blue-600 rounded-full py-1 px-2 hover:bg-blue-100 hover:text-blue-800">
                新規登録
            </a>
        </div>

        <div class="w-full">
            <form action="/contractor" method="GET">
                <div class="relative flex">
                    <input class="w-full rounded-full shadow-md h-10 px-5 pr-16 focus:border-blue-400 focus:bg-white" type="search" name="q" placeholder="検索キーワード">
                    <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                        <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                            viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                            width="512px" height="512px">
                            <path
                            d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>

    {% if contractors %}
    <div class="px-3 items-center flex mx-auto text-sm align-bottom justify-between">
        <p><span class="text-lg font-bold">{{ count }} </span>件</p>

        <p class="">
            {% if page %}
            {% for page_num in contractors.iter_pages(left_edge=3, right_edge=3) %}
            {% if page_num %}
                {% if contractors.page == page_num %}
                <a class="text-blue-600 underline" href="{{ url_for('contractor.index', q=search, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                <a class="text-blue-600" href="{{ url_for('contractor.index', q=search, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}  
        {% endif %}  
        </p>
    </div>

    <table class="table-auto w-full mx-2">
            <thead>
                <tr class="border-black border-b">
                    <td class="p-2">ID</td>
                    <td class="p-2"></td>
                    <td class="p-2">業者名</td>
                    <td class="p-2">郵便番号</td>
                    <td class="p-2">住所</td>
                </tr>
            </thead>
            <tbody>
            {% for contractor in contractors.items %}
                <tr class="">        
                    <td class="border-b"><a class="text-blue-600 hover:underline hover:text-blue-800" href="/contractor/{{ contractor.id }}">
                        {{ '%05d' % contractor.id }}</a></td>
                    <td class="border-b">
                        {% if contractor.satiscare.membership == 1 %}
                        <span class="inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-white bg-indigo-700 rounded-full">
                            ケア</span>
                        {% endif %}
                    </td>
                    <td class="border-b">{{ contractor.name }}</td>
                    <td class="border-b">{{ '{}-{}'.format(contractor.zip[:3], contractor.zip[3:]) }}</td>
                    <td class="border-b">{{ contractor.prefecture }}{{ contractor.city }}{{ contractor.town }}{{ contractor.address }}</td>
                </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

sf/app/templates/contractor/license-detail.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}

<div class="container max-w-4xl mx-auto px-2 flex-grow">
    {% include "_flashing.html" %}

    <div class="max-w-md mx-auto mt-10">
        <p class="font-bold text-lg my-5">許可情報</p>
        <div class="max-w-xl rounded shadow-lg my-5 p-5">
            <div class="">
                <p class="text-right">
                    <a href="/contractor/{{ contractor.id }}/license/{{ license.id }}/edit" class="px-2 py-1 text-blue-500 rounded-full hover:bg-blue-100 text-right text-sm">編集</a>
                </p>
            </div>

            <p class="mt-3 text-lg font-bold">{{ '%05d' % contractor.id }}</p>
            <p class="text-2xl my-2">{{ contractor.name }}</p>
            <p class="text-lg font-bold">{{ license.issuer.name }} {{ license.license_type.name }}</p>
            <p class="text-gray-700 text-sm">許可番号：
                {% if license.copy_url %}
                <a href="{{ license.copy_url }}" class="text-lg text-blue-600 hover:underline hover:text-blue-800" target="_blank" rel="noopener">
                    {{ '%03d' % license.issuer_id }}{{ license.license_type_id }}{{ license.reserved_num }}{{ license.unique_num }}
                </a>
                {% else %}
                <span>
                    {{ '%03d' % license.issuer_id }}{{ license.license_type_id }}{{ license.reserved_num }}{{ license.unique_num }}
                </span>
                {% endif %}
            </p>

            <p class="text-gray-700 text-sm">許可の年月日：
                <span class="text-lg font-bold">{{ license.effective_from }}</span>
            </p>
            <p class="text-gray-700 text-sm">許可の有効年月日：
                <span class="text-lg font-bold">{{ license.expires_on }}</span>
            </p>

            <hr class="mt-5 mb-3">

            <div class="flex justify-between text-gray-500 text-sm">
                <p class="items-end">{{ license.registered_at.strftime('%Y-%m-%d %H:%M') }}</p>
                <p class="items-end">{{ license.registered_by }}</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

sf/app/templates/contractor/license-edit.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}
{% from "_macros.html" import render_field_with_errors, render_input_field %}

<div class="container mx-auto max-w-sm py-10 flex-grow">
    <h1 class="font-bold text-xl text-gray-500">許可証情報の更新</h1>
    <h2 class="my-5 font-bold text-lg text-gray-500">{{ '%05d' % contractor.id }}: {{ contractor.name }}</h2>
        <form  x-data="{radio: ''}"
                        action="/contractor/{{ contractor.id }}/license/{{ license.id }}/edit" method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
    
            <div class="my-5 text-gray-500 align-middle">
                <p class="">許可番号<span class="text-xs ml-3 text-red-500">必須</span></p>
                <div class="flex">
                {{ render_input_field(form.issuer, class_="text-gray-700 focus:outline-none
                    focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
                -
                {{ render_input_field(form.license_type, class_="text-gray-700 focus:outline-none
                    focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
                {{ render_input_field(form.reserved_num, class_="text-gray-700 focus:outline-none
                    focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
                -
                {{ render_input_field(form.unique_num, class_="text-gray-700 focus:outline-none
                    focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", value=license.unique_num)}}
                </div>
            </div>

            <div class="my-5 text-gray-500">
                {{ render_field_with_errors(form.effective_from, class_="w-full text-gray-700 focus:outline-none
                   focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", value=license.effective_from)}}
            </div>
            <div class="my-5 text-gray-500">
                {{ render_field_with_errors(form.expires_on, class_="w-full text-gray-700 focus:outline-none
                   focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", value=license.expires_on)}}
            </div>

            <div class="my-5 text-gray-500">
                {{ render_field_with_errors(form.copy_url, class_="w-full text-gray-700 focus:outline-none
                   focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", value=license.copy_url)}}
            </div>

            <button type="button" x-on:click="$el.closest('form').submit();" class="bg-blue-600 text-white text-sm my-5 py-1 px-28 w-full rounded shadow-lg
        hover:bg-blue-800 transition duration-200">内容確認</button>
    </form>
</div>
{% endblock %}

sf/app/templates/contractor/license-register.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}
{% from "_macros.html" import render_field_with_errors, render_input_field %}

<div class="container max-w-4xl mx-auto px-2 flex-grow">

    <div class="max-w-sm mx-auto mt-10" x-data="{ open: false }">

        <h1 class="font-bold text-lg my-5">許可証情報の登録</h1>
        <h2 class="my-5 font-bold text-lg text-gray-500">{{ '%05d' % contractor.id }}: {{ contractor.name }}</h2>
            <form x-data="{ issuer: '',
                            license_type: '',
                            reserved_num: '',
                            unique_num: '',
                            effective_from: '',
                            expires_on: '',
                            copy_url: '',
                            license_copy: '',
                            select: ''
                        }" 
                action="/contractor/{{ contractor.id }}/license/register" method="POST" enctype="multipart/form-data">
                {{ form.csrf_token }}
        
                <div class="my-5 text-gray-500 align-middle">
                    <p class="">許可番号<span class="text-xs ml-3 text-red-500">必須</span></p>
                    <div class="flex">
                    {{ render_input_field(form.issuer, class_="text-gray-700 focus:outline-none
                        focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", **{'x-model':'issuer'})}}
                    -
                    {{ render_input_field(form.license_type, class_="text-gray-700 focus:outline-none
                        focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", **{'x-model':'license_type'})}}
                    {{ render_input_field(form.reserved_num, class_="text-gray-700 focus:outline-none
                        focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", **{'x-model':'reserved_num'})}}
                    -
                    {{ render_input_field(form.unique_num, class_="text-gray-700 focus:outline-none
                        focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="数字6桁"
                        , **{'x-model':'unique_num'})}}
                    </div>
                </div>
    
                <div class="my-5 text-gray-500">
                    {{ render_field_with_errors(form.effective_from, class_="w-full text-gray-700 focus:outline-none
                       focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", **{'x-model':'effective_from'})}}
                </div>
                <div class="my-5 text-gray-500">
                    {{ render_field_with_errors(form.expires_on, class_="w-full text-gray-700 focus:outline-none
                       focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", **{'x-model':'expires_on'})}}
                </div>
    
                <div class="my-5 text-gray-500">
                    <p class="">許可証写し<span class="text-xs ml-3 text-red-500">必須</span></p>
                        <div class="mt-3 text-sm flex justify-around">
                            <label class="mx-5 text-sm">Webのリンク
                                <input type="radio" name="select" class="ml-2" x-model="select" value="url"></label>
    
                            <label class="text-sm">PDFアップロード
                                <input type="radio" name="select" class="ml-2" x-model="select" value="pdf"></label>
                        </div>
                        <template x-if="select == 'url'">
                            <div class="my-5 text-gray-500">
                                {{ render_field_with_errors(form.copy_url, class_="w-full text-gray-700 focus:outline-none
                                   focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="https://から始まるURL",
                                   **{'x-model' : 'copy_url'}
                                   )}}
                            </div>    
                        </template>
    
                        <template x-if="select == 'pdf'">
                            <div class="my-5 text-gray-500">
                                {{ render_field_with_errors(form.license_copy, class_="w-full text-gray-700 focus:outline-none
                                   focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", **{'x-model' : 'license_copy'})}}
                            </div>    
                        </template>
    
                    
                    </div>
                <!-- this works onclick="submit();" -->
                <!-- this works too x-on:click="$el.closest('form').submit();" -->
                <button type="button"
                 x-on:click="issuer && license_type && reserved_num && unique_num && effective_from && expires_on && (copy_url || license_copy)
                   ? open = true : alert('未入力の項目があります。');" 
                class="bg-blue-600 text-white text-sm my-5 py-1 px-28 w-full rounded shadow-lg
            hover:bg-blue-800 transition duration-200">内容確認</button>
    
            <div x-show="open" class="fixed inset-0 bg-black bg-opacity-70 flex justify-center items-center">
    
            <div class="bg-white mx-3 md:mx-0 border p-6 shadow-md">
    
            <h2 class="font-bold text-sm">登録内容の確認</h2>
            <p class="text-gray-800 text-sm mt-5">{{ '%05d' % contractor.id }}: {{ contractor.name }}</p>
            <p class="text-gray-500 text-xs mt-2">許可番号
                <span class="ml-3 font-bold text-gray-800 text-base" x-text="issuer.padStart(3, '0')"></span>
                <span class="font-bold text-gray-800 text-base" x-text="license_type"></span>
                <span class="font-bold text-gray-800 text-base" x-text="reserved_num"></span>
                <span class="font-bold text-gray-800 text-base" x-text="unique_num"></span>
            </p>
            <p class="text-gray-500 text-xs mt-2">許可の年月日
                <span class="font-bold text-gray-800 text-base" x-text="effective_from"></span>
            </p>
            <p class="text-gray-500 text-xs mt-2">許可の有効期限
                <span class="font-bold text-gray-800 text-base" x-text="expires_on"></span>
            </p>
            <template x-if="select == 'url'">
                <p class="text-gray-500 text-xs mt-2">Webのリンク
                    <span class="font-bold text-gray-800" x-text="copy_url"></span>
                </p>    
            </template>
            <template x-if="select == 'pdf'">
                <p class="text-gray-500 text-xs mt-2">PDFアップロード
                    <span class="font-bold text-gray-800" x-text="license_copy"></span>
                </p>    
            </template>
    
            <div class="font-bold mt-5 text-right">
                <button type="button" @click="open = false" class="px-3 py-1 rounded-md text-gray-500 cursor-pointer hover:bg-gray-100">
                    戻る</button>
                <button class="ml-8 px-3 py-1 rounded-md text-rose-500 cursor-pointer hover:bg-rose-100">登録</button>
            </div>
        </div>
    </div>
    
        </form>
    </div>

</div>

{% endblock %}

sf/app/templates/contractor/register.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}
{% from "_macros.html" import render_field_with_errors, render_input_field %}

<div class="container mx-auto max-w-sm py-10">
    <h1 class="font-bold text-xl text-gray-500">パートナー登録</h1>

    <form action="/contractor/register" method="POST">
        {{ form.csrf_token }}

        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.id, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="数字1〜5桁")}}
            <div id="error_id" style="color: red;"></div>{# jsでバリエーションしてエラー表示をさせる場所 #}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.name, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="株式会社さてぃす産業")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.title, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="代表取締役")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.representative, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="小松　武司")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.zip, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="1040032")}}
        </div>
        <div class="flex my-3 text-sm">
            {{ render_input_field(form.prefecture, class_="w-full border-b px-3", readonly=True, placeholder="千葉県")}}
            {{ render_input_field(form.city, class_="w-full border-b px-3", readonly=True, placeholder="市川市")}}
            {{ render_input_field(form.town, class_="w-full border-b px-3", readonly=True, placeholder="西条")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.address, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", placeholder="三丁目12番8号")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.bldg, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-sm">{{ form.care.label(class_=" text-base text-gray-500") }}
            {{ form.care(class_="border mx-3 align-middle") }}</div>
    
        <button type="submit" class="bg-blue-600 text-white text-sm my-5 py-1 px-28 w-full rounded shadow-lg
    hover:bg-blue-800 transition duration-200">登録</button>

    </form>
</div>
{% endblock %}

{% block script %}
<!-- 住所補完JavaScriptライブラリの読み込み -->
<script type="text/javascript" src="https://postcode-jp.com/js/postcodejp.js" charset="utf-8"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/postcode.js') }}"></script>
{% endblock %}