sf/app/customer/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField
from wtforms.validators import InputRequired, NumberRange, Length

class CustomerForm(FlaskForm):
    id = IntegerField('取引先ID', validators=[InputRequired('IDを入力して下さい。'),
        NumberRange(min=1, max=999999, message='有効なIDを入力して下さい。')])
    name = StringField('取引先名', validators=[InputRequired('取引先名は必須です。')])
    title = StringField('代表者役職名')
    representative = StringField('代表者名', validators=[InputRequired('代表者名は必須です。')])
    zip = StringField('郵便番号', validators=[InputRequired('郵便番号は必須です。'),
        Length(min=7, max=7, message='郵便番号は7桁です。')])
    prefecture = StringField('都道府県', validators=[InputRequired('都道府県は必須です。')])
    city = StringField('市区町村', validators=[InputRequired('市区町村は必須です。')])
    town = StringField('町域', validators=[InputRequired('町域は必須です。')])
    address = StringField('住所')
    bldg = StringField('建物名等')


class ShopForm(FlaskForm):
    id = IntegerField('事業所番号', validators=[InputRequired('IDを入力して下さい。'),
        NumberRange(min=1, max=999999, message='有効なIDを入力して下さい。')])
    shop_number = StringField('取引先の事業所番号')
    name = StringField('事業所名', validators=[InputRequired('事業所名は必須です。')])
    zip = StringField('郵便番号', validators=[InputRequired('郵便番号は必須です。'),
        Length(min=7, max=7, message='郵便番号は7桁です。')])
    prefecture = StringField('都道府県', validators=[InputRequired('都道府県は必須です。')])
    city = StringField('市区町村', validators=[InputRequired('市区町村は必須です。')])
    town = StringField('町域', validators=[InputRequired('町域は必須です。')])
    address = StringField('住所')
    bldg = StringField('建物名等')

sf/app/customer/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

from ..extentions import db

from ..models import Customer, Shop, Contract

from .forms import CustomerForm, ShopForm

customer = Blueprint('customer', __name__, url_prefix='/customer')


# @customer.route('/parent')
# def parent():
#     parents = Parent.query.all()

#     return render_template('customer/parent.html', parents=parents)


@customer.route('/')
def index():

    q = request.args.get('q')
    page = request.args.get('page', 1, type=int)

    if q:
        search = "%{}%".format(q)
        page = request.args.get('page', 1, type=int)
        customers = Customer.query.filter(Customer.name.like(search)).paginate(page=page, per_page=20)
        count = len(Customer.query.filter(Customer.name.like(search)).all())

        return render_template('customer/index.html', page=page, customers=customers, count=count, search=search)
    
    else:
        customers = Customer.query.paginate(page=page, per_page=20)
        count = len(Customer.query.all())

        return render_template('customer/index.html', page=page, customers=customers, count=count)


@customer.route('/register', methods=['GET', 'POST'])
def register():
    form = CustomerForm()

    if form.validate_on_submit():
        id = request.form['id']
        
        # check if id already exists in the db
        exists = Customer.query.get(id)

        if exists:
            return redirect(url_for('customer.profile', id=id))

        else:
            name = request.form['name']
            title = request.form.get('title')
            representative = request.form['representative']
            zip = request.form['zip']
            prefecture = request.form['prefecture']
            city = request.form['city']
            town = request.form['town']
            address = request.form.get('address')
            bldg = request.form.get('bldg')
            registered_by = 1

            customer = Customer(id=id, name=name, title=title, representative=representative, zip=zip,
             prefecture=prefecture, city=city, town=town, address=address, bldg=bldg, registered_by=registered_by)

            db.session.add(customer)
            
            db.session.commit()

            flash('取引先を登録しました。', 'success')

            return redirect(url_for('customer.profile', id=id))

    return render_template('customer/register.html', form=form)


# show and update customer profile
@customer.route('/<int:id>')
@customer.route('/<int:id>/<mode>', methods=['GET', 'POST'])
def profile(id, mode=None):
    customer = Customer.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)

    shops = Shop.query.filter_by(customer_id=id).paginate(page=page, per_page=20)
    contracts = Contract.query.filter_by(customer_id=id).all()

    if mode == 'edit':
        form = CustomerForm(obj=customer)

        if form.validate_on_submit():
            customer.name = request.form['name']
            customer.title = request.form.get('title')
            customer.representative = request.form['representative']
            customer.zip = request.form['zip']
            customer.prefecture = request.form['prefecture']
            customer.city = request.form['city']
            customer.town = request.form['town']
            customer.address = request.form.get('address')
            customer.bldg = request.form.get('bldg')
            customer.registered_by = 1

            db.session.commit()

            flash('取引先の情報を更新しました。')

            return redirect(url_for('customer.profile', id=id))

        return render_template('customer/edit.html', form=form, customer=customer)

    return render_template('customer/profile.html', customer=customer, shops=shops, page=page, contracts=contracts)


@customer.route('/<int:id>/register', methods=['GET', 'POST'])
def shop_register(id):
    form = ShopForm()
    customer = Customer.query.get(id)

    if form.validate_on_submit():
        customer_id = customer.id
        shop_id = request.form['id']
        shop_number = request.form.get('shop_number')
        name = request.form['name']
        zip = request.form['zip']
        prefecture = request.form['prefecture']
        city = request.form['city']
        town = request.form['town']
        address = request.form.get('address')
        bldg = request.form.get('bldg')
        registered_by = 1

        # check if requested shop already exists in the db
        exists = Shop.query.get((customer_id, shop_id))

        if exists:
            return redirect(url_for('customer.shop_profile', customer_id=customer_id, id=shop_id))

        else:

            shop = Shop(customer_id=customer_id, id=shop_id, shop_number=shop_number, name=name, zip=zip,
                 prefecture=prefecture, city=city, town=town, address=address, bldg=bldg, registered_by=registered_by)

            db.session.add(shop)
    
            db.session.commit()

            flash('事業所を登録しました。', 'success')

            return redirect(url_for('customer.shop_profile', customer_id=customer_id, id=shop_id))

    return render_template('customer/shop-register.html', customer=customer, form=form)


# show and update shop profile
@customer.route('/<int:customer_id>/<int:id>')
@customer.route('/<int:customer_id>/<int:id>/<mode>', methods=['GET', 'POST'])
def shop_profile(customer_id, id, mode=None):

    shop = Shop.query.get_or_404((customer_id, id))
    contracts = Contract.query.filter_by(customer_id=customer_id).filter_by(shop_id=id).all()

    if mode == 'edit':
        form = ShopForm(obj=shop)

        if form.validate_on_submit():
            shop.shop_number = request.form.get('shop_number')
            shop.name = request.form['name']
            shop.zip = request.form['zip']
            shop.prefecture = request.form['prefecture']
            shop.city = request.form['city']
            shop.town = request.form['town']
            shop.address = request.form.get('address')
            shop.bldg = request.form.get('bldg')
            shop.registered_by = 1

            db.session.commit()

            flash('事業所の情報を更新しました。', 'success')

            return redirect(url_for('customer.shop_profile', customer_id=customer_id, id=id))

        return render_template('customer/shop-edit.html', shop=shop, form=form)

    return render_template('customer/shop-profile.html', shop=shop, contracts=contracts)

sf/app/templates/customer/edit.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}
{% from "_macros.html" import render_field_with_errors, render_input_field %}

<div class="container mx-auto max-w-sm py-10">
    <h1 class="font-bold text-xl text-gray-500">取引先情報の編集</h1>

    <form action="/customer/{{ customer.id }}/edit" method="POST">
        {{ form.csrf_token }}

        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.id, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1", readonly=True)}}
        </div>

        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.name, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.title, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.representative, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.zip, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="flex my-3 text-gray-500">
            {{ render_input_field(form.prefecture, class_="w-full border-b px-3 text-lg", readonly=true)}}
            {{ render_input_field(form.city, class_="w-full border-b px-3 text-lg", readonly=true)}}
            {{ render_input_field(form.town, class_="w-full border-b px-3 text-lg")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.address, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.bldg, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
    
        <button type="submit" class="bg-blue-600 text-white text-sm my-5 py-1 px-28 w-full rounded shadow-lg
    hover:bg-blue-800 transition duration-200">登録</button>

    </form>

</div>
{% endblock %}

{% block script %}
<!-- 住所補完JavaScriptライブラリの読み込み -->
<script type="text/javascript" src="https://postcode-jp.com/js/postcodejp.js" charset="utf-8"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/postcode.js') }}"></script>
{% endblock %}

sf/app/templates/customer/index.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}

<div class="container mx-auto max-w-4xl flex-grow">

    <div class="mx-auto my-12 max-w-md">

        <div class="flex justify-between my-5 ">
            <h1 class="font-bold text-xl text-gray-500">取引先</h1>

            <a href="/customer/register" class="text-sm text-blue-600 rounded-full py-1 px-2 hover:bg-blue-100 hover:text-blue-800">
                新規登録
            </a>
        </div>

        <div class="w-full">
            <form action="/customer" method="GET">
                <div class="relative flex">
                    <input class="w-full rounded-full shadow-md h-10 px-5 pr-16 focus:border-blue-400 focus:bg-white" type="search" name="q" placeholder="キーワード">
                    <button type="submit" class="absolute right-0 top-0 mt-3 mr-4">
                        <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
                            xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
                            viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
                            width="512px" height="512px">
                            <path
                            d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
    </div>

    {% if customers %}
    <div class="px-3 items-center flex mx-auto text-sm align-bottom justify-between">
        <p><span class="text-lg font-bold">{{ count }} </span>件</p>
        <p class="">
            {% if page %}
            {% for page_num in customers.iter_pages(left_edge=3, right_edge=3) %}
            {% if page_num %}
                {% if customers.page == page_num %}
                <a class="text-blue-600 underline" href="{{ url_for('customer.index', q=search, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                <a class="text-blue-600" href="{{ url_for('customer.index', q=search, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}  
        {% endif %}  
        </p>
    </div>

    <table class="table-auto w-full mx-2">
            <thead>
                <tr class="border-black border-b">
                    <td class="p-2">ID</td>
                    <td class="p-2">取引先名</td>
                    <td class="p-2">郵便番号</td>
                    <td class="p-2">住所</td>
                </tr>
            </thead>
            <tbody>
            {% for customer in customers.items %}
                <tr class="">
                    <td class="border-b"><a class="text-blue-600 hover:underline hover:text-blue-800" href="/customer/{{ customer.id }}">
                        {{ '%05d' % customer.id }}</a></td>
                    <td class="border-b">{{ customer.name }}</td>
                    <td class="border-b">{{ '{}-{}'.format(customer.zip[:3], customer.zip[3:]) }}</td>
                    <td class="border-b">{{ customer.prefecture }}{{ customer.city }}{{ customer.town }}{{ customer.address }}</td>
                </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

sf/app/templates/customer/parent.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}

<div class="container mx-auto max-w-4xl flex-grow">
    <div class="mx-auto my-12 max-w-md">
        <div class="flex justify-between my-5 ">
            <h1 class="font-bold text-xl text-gray-500">グループ</h1>
        </div>

        {% if parents %}
        <table class="table-auto w-full mx-auto">
            <thead>
                <tr class="border-black border-b">
                    <td class="p-2">ID</td>
                    <td class="p-2">グループ名</td>
                    <td class="p-2">登録者</td>
                    <td class="p-2">登録日</td>
                </tr>
            </thead>
    
            <tbody>
            {% for parent in parents %}
                <tr class="">
                    <td class="border-b">{{ parent.id }}</td>
                    <td class="border-b">{{ parent.name }}</td>
                    <td class="border-b">{{ parent.registered_by }}</td>
                    <td class="border-b">{{ parent.registered_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}

    </div>
</div>
{% endblock %}

sf/app/templates/customer/profile.html
{% extends "layout.html" -%}
{% block content -%}
{% include "navbar.html" -%}
{% include "_flashing.html" -%}

<div class="container max-w-2xl mx-auto mt-7 px-2 flex-grow">
    <div class="max-w-md mx-auto">
        <p class="font-bold text-lg my-5">取引先情報</p>
        <div class="max-w-xl rounded shadow-lg my-5 py-3 px-5">
            <div class="">
                <p class="text-right">
                    <a href="/customer/{{ customer.id }}/edit" class="px-2 py-1 text-blue-500 rounded-full hover:bg-blue-100 text-right text-sm">編集</a>
                </p>
                <p class="text-gray-500 text-sm">
                </p>
            </div>
            <p class="mt-3 text-lg font-bold">{{ '%05d' % customer.id }}</p>
            <p class="text-xl my-2">{{ customer.name }}</p>
            <p class="text-gray-700">{{ customer.title }} {{ customer.representative }}</p>
            <p class="text-gray-700">{{ '〒{}-{}'.format(customer.zip[:3], customer.zip[3:]) }}</p>
            <p class="text-gray-700">{{ customer.prefecture }}{{ customer.city }}{{ customer.town }}{{ customer.address }}</p>
            <p class="text-gray-700">{{ customer.bldg }}</p>
            <hr class="mt-5 mb-3">

            <div class="flex justify-between text-gray-500 text-sm">
                <p class="items-end">{{ customer.registered_at.strftime('%Y-%m-%d %H:%M') }}</p>
                <p class="items-end">{{ customer.registered_by }}</p>
            </div>
        </div>

        <!-- shops -->
        <div class="max-w-xl rounded shadow-lg my-5 p-5">

        <p class="mx-5 text-sm text-right">
            <a href="/customer/{{ customer.id }}/register" class="px-2 py-1 text-blue-500 hover:text-blue-700 hover:bg-blue-100 rounded-full">
            + 事業所の登録
            </a>
        </p>
        {% if shops %}
        <div class="">
            {% if page %}
            {% for page_num in shops.iter_pages(left_edge=3, right_edge=3) %}
            {% if page_num %}
                {% if shops.page == page_num %}
                <a class="text-blue-600 underline" href="{{ url_for('customer.profile', id=customer.id, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                <a class="text-blue-600" href="{{ url_for('customer.profile', id=customer.id, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
            ...
            {% endif %}
            {% endfor %}  
    
            {% endif %}
        </div>
        <table class="table-auto w-full m-2 text-sm">
            <thead>
                <tr class="font-bold border-black border-b">
                    <td class="px-2">ID</td>
                    <td class="px-2">事業所名</td>
                    <td class="px-2">住所</td>
                </tr>
            </thead>
            <tbody>
            {% for shop in shops.items %}
                <tr class="">
                    <td class="border-b"><a class="text-blue-600 hover:underline hover:text-blue-800" href="/customer/{{ customer.id }}/{{ shop.id }}">
                        {{ '%05d' %shop.id }}</a></td>
                    <td class="border-b">{{ shop.name }}</td>
                    <td class="border-b">{{ shop.prefecture }}{{ shop.city }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
        </div>

        <!-- contracts -->
        <div class="max-w-xl rounded shadow-lg my-5 p-5">
            <p class="mt-5 text-sm text-right">
                <a href="/contract/register/{{ customer.id }}" class="px-2 py-1 text-blue-500 rounded-full hover:bg-blue-100 text-right text-sm">
                    + 契約を登録</a>
            </p>

            {% if contracts %}
            <table class="table-auto w-full m-2 text-sm">
                <thead>
                    <tr class="font-bold border-black border-b">
                        <td class="px-2">ID</td>
                        <td class="px-2">業者名</td>
                        <td class="px-2">種類</td>
                    </tr>
                </thead>
                <tbody>
                {% for contract in contracts %}
                    <tr class="">
                        <td class="border-b"><a class="text-blue-600 hover:underline hover:text-blue-800" href="/contract/{{ contract.id }}">
                            {{ contract.id }}</a></td>
                        <td class="border-b">{{ contract.contractor.name }}</td>
                        <td class="border-b">{{ contract.item.name }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
    
        </div>


    </div>



</div>

{% endblock %}

sf/app/templates/customer/register.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}
{% from "_macros.html" import render_field_with_errors, render_input_field %}

<div class="container mx-auto max-w-sm py-10">
    <h1 class="font-bold text-xl text-gray-500">取引先登録</h1>

    <form action="/customer/register" method="POST">
        {{ form.csrf_token }}

        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.id, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
            <div id="error_id" style="color: red;"></div>{# jsでバリエーションしてエラー表示をさせる場所 #}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.name, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.title, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.representative, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.zip, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="flex my-3">
            {{ render_input_field(form.prefecture, class_="w-full border-b px-3 text-lg", readonly=True)}}
            {{ render_input_field(form.city, class_="w-full border-b px-3 text-lg", readonly=True)}}
            {{ render_input_field(form.town, class_="w-full border-b px-3 text-lg", readonly=True)}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.address, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.bldg, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
    
        <button type="submit" class="bg-blue-600 text-white text-sm my-5 py-1 px-28 w-full rounded shadow-lg
    hover:bg-blue-800 transition duration-200">登録</button>

    </form>

</div>

<!-- 住所補完JavaScriptライブラリの読み込み -->
<script type="text/javascript" src="https://postcode-jp.com/js/postcodejp.js" charset="utf-8"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/postcode.js') }}"></script>
{% endblock %}

sf/app/templates/customer/shop-edit.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}
{% from "_macros.html" import render_field_with_errors, render_input_field %}

<div class="container mx-auto max-w-sm py-10">
    <h1 class="font-bold text-xl text-gray-500">事業所情報の編集</h1>

    <form action="/customer/{{ shop.customer_id }}/{{ shop.id }}/edit" method="POST">
        {{ form.csrf_token }}

        <div class="my-5 text-gray-800 text-lg">
            {{ shop.customer_id }} - {{ form.id(readonly=True) }}
        </div>

        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.shop_number, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>

        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.name, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.zip, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="flex my-3 text-gray-500">
            {{ render_input_field(form.prefecture, class_="w-full border-b px-3 text-lg", readonly=True)}}
            {{ render_input_field(form.city, class_="w-full border-b px-3 text-lg", readonly=True)}}
            {{ render_input_field(form.town, class_="w-full border-b px-3 text-lg")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.address, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>
        <div class="my-5 text-gray-500">
            {{ render_field_with_errors(form.bldg, class_="w-full text-gray-700 focus:outline-none
               focus:bg-gray-100 border-b border-gray-300 focus:border-blue-500 px-3 pb-1")}}
        </div>

        <button type="submit" class="bg-blue-600 text-white text-sm my-5 py-1 px-28 w-full rounded shadow-lg
    hover:bg-blue-800 transition duration-200">登録</button>

    </form>

</div>
{% endblock %}

{% block script %}
<!-- 住所補完JavaScriptライブラリの読み込み -->
<script type="text/javascript" src="https://postcode-jp.com/js/postcodejp.js" charset="utf-8"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/postcode.js') }}"></script>
{% endblock %}

sf/app/templates/customer/shop_profile.html
{% extends "layout.html" %}
{% block content %}
{% include "navbar.html" %}
{% include "_flashing.html" %}

<div class="container max-w-2xl mx-auto mt-7 px-2">
    <div class="max-w-md mx-auto">
        <p class="font-bold text-lg my-5">事業所情報</p>
        <div class="max-w-xl rounded shadow-lg my-5 p-5">
            <div class="">
                <p class="text-right">
                    <a href="/customer/{{ shop.customer_id }}/{{ shop.id }}/edit" class="px-1 py-1 text-blue-500 rounded-full hover:bg-blue-100 text-right">編集</a>
                </p>
                <p class="text-gray-500 text-sm">
                </p>    
            </div>
            <p class="mt-3 text-lg font-bold">{{ shop.customer_id }}-{{ shop.id }}</p>
            <p class="text-2xl my-2">{{ shop.name }}</p>
            <p class="text-gray-700">{{ '〒{}-{}'.format(shop.zip[:3], shop.zip[3:]) }}</p>
            <p class="text-gray-700">{{ shop.prefecture }}{{ shop.city }}{{ shop.town }}{{ shop.address }}</p>
            <p class="text-gray-700">{{ shop.bldg }}</p>
            <hr class="mt-5 mb-3">

            <div class="flex justify-between text-gray-500 text-sm">
                <p class="items-end">{{ shop.registered_at.strftime('%Y-%m-%d %H:%M') }}</p>
                <p class="items-end">{{ shop.registered_by }}</p>
            </div>
        </div>
        <p class="mx-5">
            <a href="/customer/{{ shop.id }}/shop/register" class="text-blue-500 hover:text-blue-700 hover:underline">
            事業所の登録
            </a>
        </p>
    </div>
</div>

{% endblock %}